vich_uploader:
    db_driver: orm
    
    mappings:
      post_thumbnails:
        uri_prefix: /images/user
        upload_destination: '%kernel.project_dir%/public/images/user'
        namer: vich_uploader.namer_uniqid  
